Emit errors instead of throwing errors
pinojs/thread-stream pull request #94
Opened 2022-07-11 14:31 UTC by Mogztter

Since multistream is calling stream.write(data) without a try/catch we should not throw errors but emit errors (to let users decide what to do).

Reference: https://github.com/pinojs/pino/issues/1489

2022-07-11 15:31 UTC, mcollina commented
I think this would bump the major on this module, but it won't be a semver-major bump in pino.

2022-07-11 15:36 UTC, jsumners commented
Is Pino just using this module incorrectly? This is definitely a major change here. But I wonder if the issue inducing this change cannot be resolved by looking for the thrown error?

2022-07-11 16:03 UTC, mcollina requested changes

2022-07-11 16:03 UTC, mcollina commented on index.js
> +      destroy(stream, new Error('_flushSync took too long (10s)'))
I think all `Sync` methods should keep throwing. Those are often used in the shutdown phase of thread-stream and pino and we might no have an event loop at all.

2022-07-13 10:10 UTC, mcollina approved these changes
lgtm

2022-07-13 10:11 UTC, mcollina commented
Note that this won't be a functional change for pino, however it would enable @Mogztter to fix https://github.com/pinojs/pino/issues/1489.

2022-07-13 11:54 UTC, jsumners approved these changes
Looks good to me.

2022-07-13 12:46 UTC, merged